name: '✨ Feature request'
description: Suggest a new feature or enhancement
title: 'feature: <short description>'
labels: ['status:untriaged', 'type:feature']
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - P0 (Critical - Blocking core functionality)
        - P1 (High - Important for user experience)
        - P2 (Medium - Valuable enhancement)
        - P3 (Low - Nice to have)
        - P4 (Minor - Small improvement)
        - P5 (Trivial - Polish or convenience)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area would this feature affect?
      options:
        - area:core
        - area:api
        - area:build
        - area:documentation
        - area:testing
        - area:performance
        - area:refactor
        - area:api:people
        - area:api:lists
        - area:api:notes
        - area:api:objects
        - area:api:records
        - area:api:tasks
        - area:extension
        - area:integration
        - area:security
        - area:rate-limiting
        - area:error-handling
        - area:logging
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Initial status
      description: Current status of this request
      options:
        - status:untriaged
        - status:ready
        - status:blocked
        - status:needs-info
      default: 0
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or pain point this feature would address
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to happen?
      placeholder: Describe your proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other approaches have you considered?
      placeholder: Describe any alternative solutions or features you've considered

  - type: textarea
    id: use-cases
    attributes:
      label: Use cases
      description: How would this feature be used?
      placeholder: |
        1. User scenario 1...
        2. User scenario 2...
        3. User scenario 3...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: What would constitute this feature being "done"?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3

  - type: textarea
    id: impact
    attributes:
      label: Impact and benefits
      description: What value would this feature provide?
      placeholder: Describe the expected benefits and who would be impacted

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context, screenshots, or examples
