name: Feature request
description: Propose a capability or workflow improvement.
title: 'feature: <capability> (for <surface>)'
labels:
  - type:feature
  - status:untriaged
body:
  - type: markdown
    attributes:
      value: |
        Help us evaluate this request with concrete use cases and tradeoffs.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - P0
        - P1
        - P2
        - P3
        - P4
        - P5
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area would this feature affect?
      options:
        - area:core
        - area:api
        - area:build
        - area:dist
        - area:documentation
        - area:testing
        - area:performance
        - area:refactor
        - area:api:people
        - area:api:lists
        - area:api:notes
        - area:api:objects
        - area:api:records
        - area:api:tasks
        - area:extension
        - area:integration
        - area:security
        - area:rate-limiting
        - area:error-handling
        - area:logging
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One-line statement of the requested capability.
      placeholder: Add automatic object attribute validation hints for create/update tools.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What user pain this solves and why current behavior is insufficient.
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed solution
      description: Desired behavior/API/docs changes with as much specificity as possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches considered and why they are weaker.

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: |
        Explain who is affected, severity/urgency, frequency, and practical consequence.
        Include:
        - Affected users/workflows
        - Severity (annoying, blocks workflow, etc.)
        - Frequency (always/intermittent/edge case)
        - Consequence (delays, errors, extra manual work, etc.)
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Checklist that can be verified by tests/commands.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence/examples
      description: Prior art, links, snippets, or metrics.

  - type: textarea
    id: additional_information
    attributes:
      label: Additional information
      description: Extra context, constraints, or references not covered above.
