#!/bin/bash
# Script to create PRs with automatic attribution message removal
# Usage: ./scripts/create_pr.sh "PR Title" "PR Body" base_branch

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if GitHub CLI is installed
if ! command -v gh &> /dev/null; then
    echo -e "${RED}Error: GitHub CLI (gh) is not installed.${NC}"
    echo "Please install it first: https://cli.github.com/manual/installation"
    exit 1
fi

# Parse arguments
PR_TITLE="$1"
PR_BODY="$2"
BASE_BRANCH="${3:-main}"  # Default to main if not specified

if [ -z "$PR_TITLE" ] || [ -z "$PR_BODY" ]; then
    echo -e "${RED}Error: Missing required arguments.${NC}"
    echo "Usage: $0 \"PR Title\" \"PR Body\" [base_branch]"
    exit 1
fi

# Patterns to check for and remove
ATTRIBUTION_PATTERNS=(
  "Generated with Claude"
  "Generated with \\[Claude Code\\]"
  "Co-Authored-By: Claude"
  "noreply@anthropic.com"
  "Generated by AI"
  "AI-generated"
  "Generated by Claude"
  "🤖 Generated"
  "Created with Claude"
)

# Clean the PR body
CLEANED_BODY="$PR_BODY"
ATTRIBUTION_FOUND=false

for pattern in "${ATTRIBUTION_PATTERNS[@]}"; do
  if echo "$CLEANED_BODY" | grep -Eq "$pattern"; then
    echo -e "${YELLOW}Warning:${NC} PR description contains attribution: '${YELLOW}$pattern${NC}'"
    ATTRIBUTION_FOUND=true

    # Remove lines containing the pattern
    CLEANED_BODY=$(echo "$CLEANED_BODY" | sed -E "/$pattern/d")
  fi
done

if [ "$ATTRIBUTION_FOUND" = true ]; then
  echo -e "Automatically removing attribution messages from PR description..."
fi

# Create the PR using the cleaned body
echo -e "${GREEN}Creating PR with cleaned description...${NC}"
PR_URL=$(gh pr create --title "$PR_TITLE" --body "$CLEANED_BODY" --base "$BASE_BRANCH" --repo "kesslerio/attio-mcp-server")

if [ $? -eq 0 ]; then
  echo -e "${GREEN}✅ PR created successfully: $PR_URL${NC}"
else
  echo -e "${RED}Error: Failed to create PR.${NC}"
  exit 1
fi