name: Claude PR Review (labeled)

on:
  issues:
    types: [labeled] # initial trigger comes from labels
  pull_request:
    types: [synchronize, reopened] # follow-ups on pushes if label still present

concurrency:
  group: claude-pr-labeled-${{ github.event.pull_request.number || github.event.issue.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: read
  checks: read

jobs:
  review:
    # Only proceed if this is a PR (issues:labeled can also fire on pure issues)
    if: |
      (github.event_name == 'pull_request') ||
      (github.event_name == 'issues' && github.event.issue.pull_request)

    runs-on: ubuntu-latest

    steps:
      # Optional (audit egress): set to "audit" first; switch to "block" once stable
      - name: Harden Runner (egress audit)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Get PR info & determine environment
        id: decide
        uses: actions/github-script@v7
        with:
          script: |
            // Get PR number regardless of event
            const prNumber = context.payload.pull_request?.number
              ?? context.payload.issue?.number;
            if (!prNumber) {
              core.setFailed('No PR number on this event'); return;
            }

            // Always fetch the PR fresh
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            const internal = pr.head.repo.full_name === `${context.repo.owner}/${context.repo.repo}`;
            const changed = pr.changed_files || 0;

            // Optional debug (shows up in logs)
            core.info(`PR #${pr.number}: internal=${internal}, changed=${changed} files`);

            core.setOutput('internal', String(internal));
            core.setOutput('pr', String(pr.number));
            core.setOutput('sha', pr.head.sha);
            core.setOutput('changed', String(changed));

      - name: Has claude label?
        id: haslabel
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request?.number ?? context.payload.issue?.number;
            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner, repo: context.repo.repo, issue_number: prNumber, per_page: 100
            });
            const names = new Set(labels.map(l => l.name));
            const hasReview = names.has('claude:review');
            const hasUltra  = names.has('claude:ultra');
            core.setOutput('has', String(hasReview || hasUltra));
            core.setOutput('has_review', String(hasReview));
            core.setOutput('has_ultra',  String(hasUltra));

      # Fork PRs won't have repo secrets -> comment guidance and skip
      - name: Handle forks (no secrets in PR context)
        if: steps.decide.outputs.internal != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = Number('${{ steps.decide.outputs.pr }}');
            const body =
              `🔒 This is a fork PR. For security, secrets are not available in PR jobs.\n\n` +
              `To run Claude reviews with full checkout, use **Actions → Claude Trusted Review (manual)** on PR #${prNumber}, or approve a maintainer-run workflow.`;
            await github.rest.issues.createComment({
              owner: context.repo.owner, repo: context.repo.repo, issue_number: prNumber, body
            });

      - name: Exit on forks
        if: steps.decide.outputs.internal != 'true'
        run: exit 0

      - name: Checkout PR HEAD
        if: steps.decide.outputs.internal == 'true' && steps.haslabel.outputs.has == 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.decide.outputs.sha }}
          fetch-depth: 0

      - name: Claude Review (Sonnet)
        if: steps.decide.outputs.internal == 'true' && steps.haslabel.outputs.has_review == 'true'
        id: claude_sonnet
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ github.token }}
          label_trigger: 'claude:review'
          claude_args: >-
            --model claude-sonnet-4-20250514
            --max-turns 16
            --allowed-tools Read,Glob,Grep,NotebookEdit,Bash
            --output-format stream-json

      - name: Claude Review (Opus)
        if: steps.decide.outputs.internal == 'true' && steps.haslabel.outputs.has_ultra == 'true'
        id: claude_opus
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ github.token }}
          label_trigger: 'claude:ultra'
          claude_args: >-
            --model claude-opus-4-1-20250805
            --max-turns ${{ fromJSON(steps.decide.outputs.changed) > 60 && '18' || '22' }}
            --allowed-tools Read,Glob,Grep,NotebookEdit,Bash
            --output-format stream-json
          prompt: |
            Perform a PR review with full working tree access.

            Enforce:
            ## Code Quality Standards
            ### Single Responsibility Principle (SRP)
            - One class/module → one reason to change. Detect mixed concerns, many dependencies, multiple change reasons.

            ### Size Limits & Refactoring Triggers
            - Functions: ≤30–40 lines; Classes/Files: ≤500 lines; Methods per class: ≤20–30.
            - Trigger refactor on complexity or mixed concerns.

            ### Refactoring Best Practices
            - Small steps; test each change. Don't mix refactors with bug fixes.
            - Deduplicate first; add focused tests.

            ### Universal Coding Standards
            - TypeScript: prefer Record<string, unknown> over any
            - PascalCase (classes/interfaces), camelCase (functions/variables)
            - Imports: node → external → internal; remove unused
            - Commits: conventional or repo override; keep #issue linkage

            Output Markdown:
            - **Summary**
            - **Top Findings** (with code snippets/diffs)
            - **Suggested Tests** (file + test name)
            - **Quick Refactors** (incremental, SRP-aligned)
            - **Perf/Sec Notes** (explicit quick wins)
            - **Risk Level** with rationale

            If mode is **ultra**, go deeper on security, performance, concurrency, error-handling, and propose minimal diffs.

      - name: Ensure review is posted (fallback)
        if: always() && steps.decide.outputs.internal == 'true' && steps.haslabel.outputs.has == 'true'
        uses: actions/github-script@v7
        env:
          EXEC_FILE_SONNET: ${{ steps.claude_sonnet.outputs.execution_file }}
          EXEC_FILE_OPUS: ${{ steps.claude_opus.outputs.execution_file }}
          RESULT_SONNET: ${{ steps.claude_sonnet.outputs.result }}
          RESULT_OPUS: ${{ steps.claude_opus.outputs.result }}
        with:
          script: |
            const fs = require('fs');
            const prNumber = Number('${{ steps.decide.outputs.pr }}');

            // avoid duplicates when track_progress updated an existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner, repo: context.repo.repo, issue_number: prNumber, per_page: 50
            });
            if (comments.some(c =>
              /Overall Risk:|Top Findings:|Suggested Tests|Quick Refactors/i.test(c.body || '') &&
              c.user?.type === 'Bot'
            )) {
              core.info('Review comment already exists; skipping fallback.');
              process.exit(0);
            }

            let body = (process.env.RESULT_SONNET || process.env.RESULT_OPUS || '').trim();
            const execFile = process.env.EXEC_FILE_SONNET || process.env.EXEC_FILE_OPUS;
            if (!body && execFile && fs.existsSync(execFile)) {
              try {
                const data = JSON.parse(fs.readFileSync(execFile, 'utf8'));
                if (typeof data.result === 'string' && data.result.trim()) body = data.result.trim();
                else if (Array.isArray(data.turns)) {
                  for (let i = data.turns.length - 1; i >= 0; i--) {
                    const parts = (data.turns[i]?.message?.content || []).filter(x => x.type === 'text').map(x => x.text);
                    const text = parts.join('\n').trim();
                    if (text) { body = text; break; }
                  }
                }
              } catch {}
            }
            if (!body) body = '_Claude produced a review, but no formatted output was found. See logs._';

            await github.rest.issues.createComment({
              owner: context.repo.owner, repo: context.repo.repo, issue_number: prNumber, body
            });
            core.info('Posted fallback review comment.');

      # Remove claude label after review completes to prevent auto re-runs on subsequent pushes
      - name: Remove claude label (prevents auto re-run)
        if: always() && steps.decide.outputs.internal == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = Number('${{ steps.decide.outputs.pr }}');

            // Check which label was applied by looking at completed steps
            const sonnetRan = '${{ steps.claude_sonnet.outcome }}' !== '';
            const opusRan = '${{ steps.claude_opus.outcome }}' !== '';

            const labelsToRemove = [];
            if (sonnetRan) labelsToRemove.push('claude:review');
            if (opusRan) labelsToRemove.push('claude:ultra');

            for (const label of labelsToRemove) {
              try {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  name: label
                });
                core.info(`Removed ${label} label to prevent auto re-runs on future pushes.`);
              } catch (e) {
                if (e.status === 404) {
                  core.info(`Label ${label} was already removed.`);
                } else {
                  core.warning(`Failed to remove label ${label}: ${e.message}`);
                }
              }
            }
